DELIMITER ;;
DROP PROCEDURE IF EXISTS `sp_merge_data` ;;
CREATE PROCEDURE `sp_merge_data` (IN _srcServerUid INT, IN _targetServerUid INT, IN _srcDBName VARCHAR(64), IN _targetDBName VARCHAR(64))
BEGIN
	DECLARE _result VARCHAR(64) DEFAULT 'Ok';
	DECLARE l_sql VARCHAR(1024);
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		SET _result = 'Failed';
		SELECT _result;
	END;
	START TRANSACTION;
	IF EXISTS(SELECT * FROM `merge_history` WHERE serverUid=_srcServerUid) THEN
		SET _result = 'Already Merged, skip';
	ELSE
		SELECT 'BEGIN source sp_mergeOccupantGift';
		SET l_sql=CONCAT('CALL `', _srcDBName, '`.`sp_mergeOccupantGift`();');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END source sp_mergeOccupantGift';
		SELECT 'BEGIN target sp_mergeOccupantGift';
		CALL `sp_mergeOccupantGift`();
		SELECT 'END target sp_mergeOccupantGift';
		SELECT 'BEGIN source sp_mergeAresGift';
		SET l_sql=CONCAT('CALL `', _srcDBName, '`.`sp_mergeAresGift`();');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END source sp_mergeAresGift';
		SELECT 'BEGIN target sp_mergeAresGift';
		CALL `sp_mergeAresGift`();
		SELECT 'END target sp_mergeAresGift';
		SELECT 'BEGIN source sp_mergeSoulPvpGift';
		SET l_sql=CONCAT('CALL `', _srcDBName, '`.`sp_mergeSoulPvpGift`();');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END source sp_mergeSoulPvpGift';
		SELECT 'BEGIN target sp_mergeSoulPvpGift';
		CALL `sp_mergeSoulPvpGift`();
		SELECT 'END target sp_mergeSoulPvpGift';
		SELECT 'BEGIN source sp_mergeUnionBattleGift';
		SET l_sql=CONCAT('CALL `', _srcDBName, '`.`sp_mergeUnionBattleGift`();');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END source sp_mergeUnionBattleGift';
		SELECT 'BEGIN target sp_mergeUnionBattleGift';
		CALL `sp_mergeUnionBattleGift`();
		SELECT 'END target sp_mergeUnionBattleGift';
		SELECT 'BEGIN ares';
		SET l_sql=CONCAT('INSERT INTO `ares` SELECT * FROM `', _srcDBName, '`.`ares` WHERE `type`!=1;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		DELETE FROM `ares` WHERE `type`=1;
		UPDATE `ares` SET rankKey=0;
		SELECT 'END ares';
		SELECT 'BEGIN areslog';
		DELETE FROM `areslog`;
		SELECT 'END areslog';
		SELECT 'BEGIN occupant';
		DELETE FROM `occupant`;
		SELECT 'END occupant';
		SELECT 'BEGIN soulpvp';
		DELETE FROM `soulpvp`;
		SELECT 'END soulpvp';
		SELECT 'BEGIN soulpvplog';
		DELETE FROM `soulpvplog`;
		SELECT 'END soulpvplog';
		SELECT 'BEGIN unionanimal';
		DELETE FROM `unionanimal`;
		SELECT 'END unionanimal';
		SELECT 'BEGIN achieve';
		SET l_sql=CONCAT('INSERT INTO `achieve` SELECT * FROM `', _srcDBName, '`.`achieve`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END achieve';
		SELECT 'BEGIN activity';
		SET l_sql=CONCAT('INSERT INTO `activity` SELECT * FROM `', _srcDBName, '`.`activity`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END activity';
		SELECT 'BEGIN activitycd';
		SET l_sql=CONCAT('INSERT INTO `activitycd` SELECT * FROM `', _srcDBName, '`.`activitycd`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END activitycd';
		SELECT 'BEGIN advance';
		SET l_sql=CONCAT('INSERT INTO `advance` SELECT * FROM `', _srcDBName, '`.`advance`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END advance';
		SELECT 'BEGIN alchemy';
		SET l_sql=CONCAT('INSERT INTO `alchemy` SELECT * FROM `', _srcDBName, '`.`alchemy`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END alchemy';
		SELECT 'BEGIN areasco';
		SET l_sql=CONCAT('INSERT INTO `areasco` SELECT * FROM `', _srcDBName, '`.`areasco`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END areasco';
		SELECT 'BEGIN artifact';
		SET l_sql=CONCAT('INSERT INTO `artifact` SELECT * FROM `', _srcDBName, '`.`artifact`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END artifact';
		SELECT 'BEGIN askmagic';
		SET l_sql=CONCAT('INSERT INTO `askmagic` SELECT * FROM `', _srcDBName, '`.`askmagic`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END askmagic';
		SELECT 'BEGIN assets';
		SET l_sql=CONCAT('INSERT INTO `assets` SELECT * FROM `', _srcDBName, '`.`assets`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END assets';
		SELECT 'BEGIN asyncpvp';
		SET l_sql=CONCAT('INSERT INTO `asyncpvp` SELECT * FROM `', _srcDBName, '`.`asyncpvp`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END asyncpvp';
		SELECT 'BEGIN asyncpvpbless';
		SET l_sql=CONCAT('INSERT INTO `asyncpvpbless` SELECT * FROM `', _srcDBName, '`.`asyncpvpbless`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END asyncpvpbless';
		SELECT 'BEGIN asyncpvprival';
		SET l_sql=CONCAT('INSERT INTO `asyncpvprival`(`roleID`,`otherID`,`otherType`,`lingliLost`) SELECT `roleID`,`otherID`,`otherType`,`lingliLost` FROM `', _srcDBName, '`.`asyncpvprival`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END asyncpvprival';
		SELECT 'BEGIN attribute';
		SET l_sql=CONCAT('INSERT INTO `attribute` SELECT * FROM `', _srcDBName, '`.`attribute`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END attribute';
		SELECT 'BEGIN chart_black';
		SET l_sql=CONCAT('INSERT INTO `chart_black` SELECT * FROM `', _srcDBName, '`.`chart_black`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END chart_black';
		SELECT 'BEGIN chartprize';
		SET l_sql=CONCAT('INSERT INTO `chartprize` SELECT * FROM `', _srcDBName, '`.`chartprize`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END chartprize';
		SELECT 'BEGIN chartreward';
		SET l_sql=CONCAT('INSERT INTO `chartreward` SELECT * FROM `', _srcDBName, '`.`chartreward`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END chartreward';
		SELECT 'BEGIN chartrewardgettime';
		SET l_sql=CONCAT('INSERT INTO `chartrewardgettime` SELECT * FROM `', _srcDBName, '`.`chartrewardgettime`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END chartrewardgettime';
		SELECT 'BEGIN climb';
		SET l_sql=CONCAT('INSERT INTO `climb` SELECT * FROM `', _srcDBName, '`.`climb`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END climb';
		SELECT 'BEGIN coliseum';
		SET l_sql=CONCAT('INSERT INTO `coliseum` SELECT * FROM `', _srcDBName, '`.`coliseum`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END coliseum';
		SELECT 'BEGIN exchange';
		SET l_sql=CONCAT('INSERT INTO `exchange` SELECT * FROM `', _srcDBName, '`.`exchange`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END exchange';
		SELECT 'BEGIN fashion';
		SET l_sql=CONCAT('INSERT INTO `fashion` SELECT * FROM `', _srcDBName, '`.`fashion`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END fashion';
		SELECT 'BEGIN forbid_list';
		SET l_sql=CONCAT('INSERT INTO `forbid_list` SELECT * FROM `', _srcDBName, '`.`forbid_list`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END forbid_list';
		SELECT 'BEGIN friend';
		SET l_sql=CONCAT('INSERT INTO `friend` SELECT * FROM `', _srcDBName, '`.`friend`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END friend';
		SELECT 'BEGIN friendapply';
		SET l_sql=CONCAT('INSERT INTO `friendapply` SELECT * FROM `', _srcDBName, '`.`friendapply`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END friendapply';
		SELECT 'BEGIN friendphysical';
		SET l_sql=CONCAT('INSERT IGNORE INTO `friendphysical` SELECT * FROM `', _srcDBName, '`.`friendphysical`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END friendphysical';
		SELECT 'BEGIN gift';
		SET l_sql=CONCAT('INSERT INTO `gift` SELECT * FROM `', _srcDBName, '`.`gift`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END gift';
		SELECT 'BEGIN giftusenum';
		SET l_sql=CONCAT('INSERT INTO `giftusenum`(`roleID`,`giftID`,`useNum`) SELECT `roleID`,`giftID`,`useNum` FROM `', _srcDBName, '`.`giftusenum`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END giftusenum';
		SELECT 'BEGIN item';
		SET l_sql=CONCAT('INSERT INTO `item` SELECT * FROM `', _srcDBName, '`.`item`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END item';
		SELECT 'BEGIN limitgoods';
		SET l_sql=CONCAT('INSERT INTO `limitgoods` SELECT * FROM `', _srcDBName, '`.`limitgoods`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END limitgoods';
		SELECT 'BEGIN logingift';
		SET l_sql=CONCAT('INSERT INTO `logingift` SELECT * FROM `', _srcDBName, '`.`logingift`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END logingift';
		SELECT 'BEGIN magicoutput';
		SET l_sql=CONCAT('INSERT INTO `magicoutput` SELECT * FROM `', _srcDBName, '`.`magicoutput`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END magicoutput';
		SELECT 'BEGIN magicsoul';
		SET l_sql=CONCAT('INSERT INTO `magicsoul` SELECT * FROM `', _srcDBName, '`.`magicsoul`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END magicsoul';
		SELECT 'BEGIN mail';
		SET l_sql=CONCAT('INSERT INTO `mail`(`roleID`,`sendID`,`sendName`,`theme`,`content`,`mailState`,`sendType`,`sendTime`,`itemID_0`,`itemNum_0`,`itemID_1`,`itemNum_1`,`itemID_2`,`itemNum_2`,`itemID_3`,`itemNum_3`,`itemID_4`,`itemNum_4`,`sendUid`) SELECT `roleID`,`sendID`,`sendName`,`theme`,`content`,`mailState`,`sendType`,`sendTime`,`itemID_0`,`itemNum_0`,`itemID_1`,`itemNum_1`,`itemID_2`,`itemNum_2`,`itemID_3`,`itemNum_3`,`itemID_4`,`itemNum_4`,`sendUid` FROM `', _srcDBName, '`.`mail`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END mail';
		SELECT 'BEGIN marrygift';
		SET l_sql=CONCAT('INSERT INTO `marrygift` SELECT * FROM `', _srcDBName, '`.`marrygift`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END marrygift';
		SELECT 'BEGIN marryinfo';
		SET l_sql=CONCAT('INSERT INTO `marryinfo` SELECT * FROM `', _srcDBName, '`.`marryinfo`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END marryinfo';
		SELECT 'BEGIN marrylog';
		SET l_sql=CONCAT('INSERT INTO `marrylog` SELECT * FROM `', _srcDBName, '`.`marrylog`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END marrylog';
		SELECT 'BEGIN marrymsg';
		SET l_sql=CONCAT('INSERT INTO `marrymsg` SELECT * FROM `', _srcDBName, '`.`marrymsg`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END marrymsg';
		SELECT 'BEGIN merge_history';
		SET l_sql=CONCAT('INSERT INTO `merge_history` SELECT * FROM `', _srcDBName, '`.`merge_history`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END merge_history';
		SELECT 'BEGIN minesweep';
		SET l_sql=CONCAT('INSERT INTO `minesweep` SELECT * FROM `', _srcDBName, '`.`minesweep`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END minesweep';
		SELECT 'BEGIN misfinish';
		SET l_sql=CONCAT('INSERT INTO `misfinish` SELECT * FROM `', _srcDBName, '`.`misfinish`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END misfinish';
		SELECT 'BEGIN misgroup';
		SET l_sql=CONCAT('INSERT INTO `misgroup` SELECT * FROM `', _srcDBName, '`.`misgroup`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END misgroup';
		SELECT 'BEGIN mission';
		SET l_sql=CONCAT('INSERT INTO `mission` SELECT * FROM `', _srcDBName, '`.`mission`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END mission';
		SELECT 'BEGIN monthcardreceive';
		SET l_sql=CONCAT('INSERT INTO `monthcardreceive` SELECT * FROM `', _srcDBName, '`.`monthcardreceive`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END monthcardreceive';
		SELECT 'BEGIN newplayer';
		SET l_sql=CONCAT('INSERT INTO `newplayer` SELECT * FROM `', _srcDBName, '`.`newplayer`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END newplayer';
		SELECT 'BEGIN niudan';
		SET l_sql=CONCAT('INSERT INTO `niudan` SELECT * FROM `', _srcDBName, '`.`niudan`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END niudan';
		SELECT 'BEGIN noticeinfo';
		SET l_sql=CONCAT('INSERT INTO `noticeinfo` SELECT * FROM `', _srcDBName, '`.`noticeinfo`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END noticeinfo';
		SELECT 'BEGIN operateinfo';
		SET l_sql=CONCAT('INSERT INTO `operateinfo` SELECT * FROM `', _srcDBName, '`.`operateinfo`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END operateinfo';
		SELECT 'BEGIN operatereward';
		SET l_sql=CONCAT('INSERT INTO `operatereward` SELECT * FROM `', _srcDBName, '`.`operatereward`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END operatereward';
		SELECT 'BEGIN pets';
		SET l_sql=CONCAT('INSERT INTO `pets` SELECT * FROM `', _srcDBName, '`.`pets`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END pets';
		SELECT 'BEGIN petsattribute';
		SET l_sql=CONCAT('INSERT INTO `petsattribute` SELECT * FROM `', _srcDBName, '`.`petsattribute`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END petsattribute';
		SELECT 'BEGIN physical';
		SET l_sql=CONCAT('INSERT INTO `physical` SELECT * FROM `', _srcDBName, '`.`physical`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END physical';
		SELECT 'BEGIN playermagic';
		SET l_sql=CONCAT('INSERT INTO `playermagic` SELECT * FROM `', _srcDBName, '`.`playermagic`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END playermagic';
		SELECT 'BEGIN playeroffer';
		SET l_sql=CONCAT('INSERT INTO `playeroffer` SELECT * FROM `', _srcDBName, '`.`playeroffer`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END playeroffer';
		SELECT 'BEGIN playersignout';
		SET l_sql=CONCAT('INSERT INTO `playersignout` SELECT * FROM `', _srcDBName, '`.`playersignout`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END playersignout';
		SELECT 'BEGIN qqmembergift';
		UPDATE `qqmembergift` SET serverID=_targetServerUid WHERE serverID=0;
		SET l_sql=CONCAT('UPDATE `', _srcDBName, '`.`qqmembergift` SET serverID=? WHERE serverID=0;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		SET @arg=_srcServerUid;
		EXECUTE s1 USING @arg;
		DEALLOCATE PREPARE s1;
		SET l_sql=CONCAT('INSERT INTO `qqmembergift` SELECT * FROM `', _srcDBName, '`.`qqmembergift`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END qqmembergift';
		SELECT 'BEGIN recharge';
		SET l_sql=CONCAT('INSERT INTO `recharge`(`roleID`,`rechargeType`,`validate`,`appCode`,`buyID`) SELECT `roleID`,`rechargeType`,`validate`,`appCode`,`buyID` FROM `', _srcDBName, '`.`recharge`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END recharge';
		SELECT 'BEGIN rewardmis';
		SET l_sql=CONCAT('INSERT INTO `rewardmis` SELECT * FROM `', _srcDBName, '`.`rewardmis`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END rewardmis';
		SELECT 'BEGIN role';
		UPDATE `role` SET serverUid=_targetServerUid WHERE serverUid=0;
		SET l_sql=CONCAT('UPDATE `', _srcDBName, '`.`role` SET serverUid=? WHERE serverUid=0;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		SET @arg=_srcServerUid;
		EXECUTE s1 USING @arg;
		DEALLOCATE PREPARE s1;
		SET l_sql=CONCAT('INSERT INTO `role` SELECT * FROM `', _srcDBName, '`.`role`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END role';
		SELECT 'BEGIN rolejjc';
		SET l_sql=CONCAT('INSERT INTO `rolejjc` SELECT * FROM `', _srcDBName, '`.`rolejjc`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END rolejjc';
		SELECT 'BEGIN rolestory';
		SET l_sql=CONCAT('INSERT INTO `rolestory` SELECT * FROM `', _srcDBName, '`.`rolestory`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END rolestory';
		SELECT 'BEGIN roletemple';
		SET l_sql=CONCAT('INSERT INTO `roletemple` SELECT * FROM `', _srcDBName, '`.`roletemple`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END roletemple';
		SELECT 'BEGIN rune';
		SET l_sql=CONCAT('INSERT INTO `rune` SELECT * FROM `', _srcDBName, '`.`rune`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END rune';
		SELECT 'BEGIN shop';
		SET l_sql=CONCAT('INSERT INTO `shop` SELECT * FROM `', _srcDBName, '`.`shop`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END shop';
		SELECT 'BEGIN shoplingli';
		SET l_sql=CONCAT('INSERT INTO `shoplingli`(`roleID`,`exchangeID`,`buyCount`) SELECT `roleID`,`exchangeID`,`buyCount` FROM `', _srcDBName, '`.`shoplingli`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END shoplingli';
		SELECT 'BEGIN skill';
		SET l_sql=CONCAT('INSERT INTO `skill` SELECT * FROM `', _srcDBName, '`.`skill`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END skill';
		SELECT 'BEGIN soul';
		SET l_sql=CONCAT('INSERT INTO `soul` SELECT * FROM `', _srcDBName, '`.`soul`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END soul';
		SELECT 'BEGIN soulsuccinct';
		SET l_sql=CONCAT('INSERT INTO `soulsuccinct` SELECT * FROM `', _srcDBName, '`.`soulsuccinct`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END soulsuccinct';
		SELECT 'BEGIN succinctinfo';
		SET l_sql=CONCAT('INSERT INTO `succinctinfo` SELECT * FROM `', _srcDBName, '`.`succinctinfo`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END succinctinfo';
		SELECT 'BEGIN suit';
		SET l_sql=CONCAT('INSERT INTO `suit` SELECT * FROM `', _srcDBName, '`.`suit`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END suit';
		SELECT 'BEGIN title';
		SET l_sql=CONCAT('INSERT INTO `title` SELECT * FROM `', _srcDBName, '`.`title`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END title';
		SELECT 'BEGIN tomarry';
		SET l_sql=CONCAT('INSERT INTO `tomarry` SELECT * FROM `', _srcDBName, '`.`tomarry`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END tomarry';
		SELECT 'BEGIN unionapply';
		SET l_sql=CONCAT('INSERT INTO `unionapply` SELECT * FROM `', _srcDBName, '`.`unionapply`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END unionapply';
		SELECT 'BEGIN unionculture';
		SET l_sql=CONCAT('INSERT INTO `unionculture` SELECT * FROM `', _srcDBName, '`.`unionculture`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END unionculture';
		SELECT 'BEGIN uniondata';
		SET l_sql=CONCAT('INSERT INTO `uniondata` SELECT * FROM `', _srcDBName, '`.`uniondata`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END uniondata';
		SELECT 'BEGIN unionfightdamage';
		SET l_sql=CONCAT('INSERT INTO `unionfightdamage` SELECT * FROM `', _srcDBName, '`.`unionfightdamage`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END unionfightdamage';
		SELECT 'BEGIN uniongiftreceive';
		SET l_sql=CONCAT('INSERT INTO `uniongiftreceive` SELECT * FROM `', _srcDBName, '`.`uniongiftreceive`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END uniongiftreceive';
		SELECT 'BEGIN uniongiftsend';
		SET l_sql=CONCAT('INSERT INTO `uniongiftsend` SELECT * FROM `', _srcDBName, '`.`uniongiftsend`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END uniongiftsend';
		SELECT 'BEGIN unioninfo';
		UPDATE `unioninfo` SET isRegister=1,isDuke=0 WHERE isDuke>0;
		SET l_sql=CONCAT('UPDATE `', _srcDBName, '`.`unioninfo` SET isRegister=1,isDuke=0 WHERE isDuke>0;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SET l_sql=CONCAT('INSERT INTO `unioninfo` SELECT * FROM `', _srcDBName, '`.`unioninfo`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END unioninfo';
		SELECT 'BEGIN unionlog';
		SET l_sql=CONCAT('INSERT INTO `unionlog` SELECT * FROM `', _srcDBName, '`.`unionlog`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END unionlog';
		SELECT 'BEGIN unionmagic';
		SET l_sql=CONCAT('INSERT INTO `unionmagic` SELECT * FROM `', _srcDBName, '`.`unionmagic`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END unionmagic';
		SELECT 'BEGIN unionmember';
		SET l_sql=CONCAT('INSERT INTO `unionmember` SELECT * FROM `', _srcDBName, '`.`unionmember`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END unionmember';
		SELECT 'BEGIN unionsDamage';
		SET l_sql=CONCAT('INSERT INTO `unionsDamage` SELECT * FROM `', _srcDBName, '`.`unionsDamage`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END unionsDamage';
		SELECT 'BEGIN unionsdamage';
		SET l_sql=CONCAT('INSERT INTO `unionsdamage` SELECT * FROM `', _srcDBName, '`.`unionsdamage`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END unionsdamage';
		SELECT 'BEGIN unionshop';
		SET l_sql=CONCAT('INSERT INTO `unionshop` SELECT * FROM `', _srcDBName, '`.`unionshop`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END unionshop';
		SELECT 'BEGIN uniontemple';
		SET l_sql=CONCAT('INSERT INTO `uniontemple` SELECT * FROM `', _srcDBName, '`.`uniontemple`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END uniontemple';
		SELECT 'BEGIN vipinfo';
		SET l_sql=CONCAT('INSERT INTO `vipinfo` SELECT * FROM `', _srcDBName, '`.`vipinfo`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END vipinfo';
		SELECT 'BEGIN wedding';
		SET l_sql=CONCAT('INSERT INTO `wedding` SELECT * FROM `', _srcDBName, '`.`wedding`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END wedding';
		SELECT 'BEGIN worldboss';
		SET l_sql=CONCAT('INSERT INTO `worldboss` SELECT * FROM `', _srcDBName, '`.`worldboss`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END worldboss';
		SELECT 'BEGIN xuanyan';
		SET l_sql=CONCAT('INSERT INTO `xuanyan` SELECT * FROM `', _srcDBName, '`.`xuanyan`;');
		SET @sql=l_sql;
		PREPARE s1 FROM @sql;
		EXECUTE s1;
		DEALLOCATE PREPARE s1;
		SELECT 'END xuanyan';
		INSERT INTO merge_history(serverUid,targetUid) VALUES(_srcServerUid,_targetServerUid);
	END IF;
	COMMIT;
	SELECT _result;
END ;;
DELIMITER ;
