/**
 * created by LiJianhua
 * 2015-06-08
 * event const
 */
module.exports = {
    OPERATE_EVENT_REWARD_BY_CONSUME_YUAN_BAO:'OPERATE_EVENT_REWARD_BY_CONSUME_YUAN_BAO',
    OPERATE_EVENT_REWARD_BY_CONSUME_PHYSICAL:'OPERATE_EVENT_REWARD_BY_CONSUME_PHYSICAL',
    OPERATE_EVENT_REWARD_BY_LEVEL_UP:'OPERATE_EVENT_REWARD_BY_LEVEL_UP',
    OPERATE_EVENT_REWARD_BY_ZHAN_LI:'OPERATE_EVENT_REWARD_BY_ZHAN_LI',
    OPERATE_EVENT_REWARD_BY_RECHARGE:'OPERATE_EVENT_REWARD_BY_RECHARGE',
    OPERATE_EVENT_REWARD_BY_CHART_YUAN_BAO:'OPERATE_EVENT_REWARD_BY_CHART_YUAN_BAO',
    OPERATE_EVENT_REWARD_BY_CHEST_POINT:'OPERATE_EVENT_REWARD_BY_CHEST_POINT'
}